CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar,
    birthday DATE
);

CREATE TABLE IF NOT EXISTS genre
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30)
);

CREATE TABLE IF NOT EXISTS mpa
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(10)
);

CREATE TABLE IF NOT EXISTS films
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(40) NOT NULL,
    description varchar CHECK description < 200,
    releaseDate DATE,
    duration    INTEGER,
    id_mpa      INTEGER REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS likes_film
(
    id_film INTEGER REFERENCES films (id),
    id_user INTEGER REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS genres_film
(
    id_film INTEGER REFERENCES films (id),
    id_genre INTEGER REFERENCES genre (id)
);

CREATE TABLE IF NOT EXISTS friends_user
(
    id_first_user  INTEGER REFERENCES users (id),
    id_second_user INTEGER REFERENCES users (id),
);